# NUMPY FUNCTIONS FOR DATA SCIENCE

## https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

## Mathematical functions

### Trigonometric functions
sin(x, /[, out, where, casting, order, ...]) 	Trigonometric sine, element-wise.
cos(x, /[, out, where, casting, order, ...]) 	Cosine element-wise.
tan(x, /[, out, where, casting, order, ...]) 	Compute tangent element-wise.

### Hyperbolic functions
sinh(x, /[, out, where, casting, order, ...]) 	Hyperbolic sine, element-wise.
cosh(x, /[, out, where, casting, order, ...]) 	Hyperbolic cosine, element-wise.
tanh(x, /[, out, where, casting, order, ...]) 	Compute hyperbolic tangent element-wise.

### Rounding
around(a[, decimals, out]) 	Evenly round to the given number of decimals.
round_(a[, decimals, out]) 	Round an array to the given number of decimals.
rint(x, /[, out, where, casting, order, ...]) 	Round elements of the array to the nearest integer.
fix(x[, out]) 	Round to nearest integer towards zero.
floor(x, /[, out, where, casting, order, ...]) 	Return the floor of the input, element-wise.
ceil(x, /[, out, where, casting, order, ...]) 	Return the ceiling of the input, element-wise.
trunc(x, /[, out, where, casting, order, ...]) 	Return the truncated value of the input, element-wise.

### Sums, products, differences¶
prod(a[, axis, dtype, out, keepdims]) 	Return the product of array elements over a given axis.
sum(a[, axis, dtype, out, keepdims]) 	Sum of array elements over a given axis.
nanprod(a[, axis, dtype, out, keepdims]) 	Return the product of array elements over a given axis treating Not a Numbers (NaNs) as ones.
nansum(a[, axis, dtype, out, keepdims]) 	Return the sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.
cumprod(a[, axis, dtype, out]) 	Return the cumulative product of elements along a given axis.
cumsum(a[, axis, dtype, out]) 	Return the cumulative sum of the elements along a given axis.
nancumprod(a[, axis, dtype, out]) 	Return the cumulative product of array elements over a given axis treating Not a Numbers (NaNs) as one.
nancumsum(a[, axis, dtype, out]) 	Return the cumulative sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.
diff(a[, n, axis]) 	Calculate the n-th discrete difference along given axis.
ediff1d(ary[, to_end, to_begin]) 	The differences between consecutive elements of an array.
gradient(f, *varargs, **kwargs) 	Return the gradient of an N-dimensional array.
cross(a, b[, axisa, axisb, axisc, axis]) 	Return the cross product of two (arrays of) vectors.
trapz(y[, x, dx, axis]) 	Integrate along the given axis using the composite trapezoidal rule.

### Exponents and logarithms
exp(x, /[, out, where, casting, order, ...]) 	Calculate the exponential of all elements in the input array.
expm1(x, /[, out, where, casting, order, ...]) 	Calculate exp(x) - 1 for all elements in the array.
exp2(x, /[, out, where, casting, order, ...]) 	Calculate 2**p for all p in the input array.
log(x, /[, out, where, casting, order, ...]) 	Natural logarithm, element-wise.
log10(x, /[, out, where, casting, order, ...]) 	Return the base 10 logarithm of the input array, element-wise.
log2(x, /[, out, where, casting, order, ...]) 	Base-2 logarithm of x.

### Arithmetic operations
add(x1, x2, /[, out, where, casting, order, ...]) 	Add arguments element-wise.
reciprocal(x, /[, out, where, casting, ...]) 	Return the reciprocal of the argument, element-wise.
negative(x, /[, out, where, casting, order, ...]) 	Numerical negative, element-wise.
multiply(x1, x2, /[, out, where, casting, ...]) 	Multiply arguments element-wise.
divide(x1, x2, /[, out, where, casting, ...]) 	Divide arguments element-wise.
power(x1, x2, /[, out, where, casting, ...]) 	First array elements raised to powers from second array, element-wise.
subtract(x1, x2, /[, out, where, casting, ...]) 	Subtract arguments, element-wise.
true_divide(x1, x2, /[, out, where, ...]) 	Returns a true division of the inputs, element-wise.
floor_divide(x1, x2, /[, out, where, ...]) 	Return the largest integer smaller or equal to the division of the inputs.
float_power(x1, x2, /[, out, where, ...]) 	First array elements raised to powers from second array, element-wise.
fmod(x1, x2, /[, out, where, casting, ...]) 	Return the element-wise remainder of division.
mod(x1, x2, /[, out, where, casting, order, ...]) 	Return element-wise remainder of division.
modf(x[, out1, out2], / [[, out, where, ...]) 	Return the fractional and integral parts of an array, element-wise.
remainder(x1, x2, /[, out, where, casting, ...]) 	Return element-wise remainder of division.
divmod(x1, x2[, out1, out2], / [[, out, ...]) 	Return element-wise quotient and remainder simultaneously.

### Handling complex numbers
angle(z[, deg]) 	Return the angle of the complex argument.
real(val) 	Return the real part of the complex argument.
imag(val) 	Return the imaginary part of the complex argument.
conj(x, /[, out, where, casting, order, ...]) 	Return the complex conjugate, element-wise. 

### Miscellaneous
convolve(a, v[, mode]) 	Returns the discrete, linear convolution of two one-dimensional sequences.
clip(a, a_min, a_max[, out]) 	Clip (limit) the values in an array.
sqrt(x, /[, out, where, casting, order, ...]) 	Return the positive square-root of an array, element-wise.
cbrt(x, /[, out, where, casting, order, ...]) 	Return the cube-root of an array, element-wise.
square(x, /[, out, where, casting, order, ...]) 	Return the element-wise square of the input.
absolute(x, /[, out, where, casting, order, ...]) 	Calculate the absolute value element-wise.
fabs(x, /[, out, where, casting, order, ...]) 	Compute the absolute values element-wise.
sign(x, /[, out, where, casting, order, ...]) 	Returns an element-wise indication of the sign of a number.
heaviside(x1, x2, /[, out, where, casting, ...]) 	Compute the Heaviside step function.
maximum(x1, x2, /[, out, where, casting, ...]) 	Element-wise maximum of array elements.
minimum(x1, x2, /[, out, where, casting, ...]) 	Element-wise minimum of array elements.
fmax(x1, x2, /[, out, where, casting, ...]) 	Element-wise maximum of array elements.
fmin(x1, x2, /[, out, where, casting, ...]) 	Element-wise minimum of array elements.
nan_to_num(x[, copy]) 	Replace nan with zero and inf with finite numbers.
real_if_close(a[, tol]) 	If complex input returns a real array if complex parts are close to zero.
interp(x, xp, fp[, left, right, period]) 	One-dimensional linear interpolation.

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import math
import operator
import os

In [2]:
#reminder in a division
np.remainder(5,3)

2

In [3]:
#summing values in an array
mynums = [1,2,3,4,5,6,7,8,9,10 
np.sum(mynums)

55

In [4]:
# adding two values
np.add(3,5)

8

In [9]:
#Trigonometry Cosine
np.cos(60)

-0.9524129804151563

In [10]:
#Trigonometry Sine
np.sin(30)

-0.9880316240928618

In [14]:
#Round down
myarray = [0.4,1.7,3.01,9.9]
np.floor(myarray)

array([0., 1., 3., 9.])

In [15]:
#Round up
np.ceil(myarray)

array([ 1.,  2.,  4., 10.])

In [20]:
#Reciprocal
np.reciprocal(2.)

0.5

In [21]:
np.reciprocal(3.)

0.3333333333333333

In [22]:
#Real numbers
a = np.array([1+2j, 3+4j, 5+6j])
a.real

array([1., 3., 5.])

In [23]:
#Conjugate
np.conjugate(1+2j)

(1-2j)

In [24]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [25]:
x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)

array([[1.-1.j, 0.-0.j],
       [0.-0.j, 1.-1.j]])